Fix issue where a None argument breaks PypircFile
Default the PypircFile constructor's keyword argument 'filename' to
None, and if None then set to '~/.pypirc`.

Previously it was possible for None values to slip into
os.path.expanduser(), resulting in an AttributeError: 'NoneType'
object has no attribute 'startswith'.

Fixes issue #185